"""HTTP routes for the meal-planner API."""
from __future__ import annotations

from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy import text
from sqlalchemy.orm import Session

from ..db import get_db
from ..models import Plan, RecipeSteps
from ..planning import coupons, llm
from ..planning.planner import PlanRequest, generate_plan
from ..planning.recipes import CORE_IDS, RECIPES, RECIPES_BY_ID
from ..schemas import (
    Coupon,
    IngredientOut,
    PlanOut,
    PlanRequestIn,
    RecipeOut,
    StepsOut,
)

router = APIRouter()


@router.get("/health", tags=["ops"])
def health(db: Session = Depends(get_db)) -> dict:
    """Liveness + DB connectivity, for Compose/k8s probes."""
    try:
        db.execute(text("SELECT 1"))
        db_ok = True
    except Exception:
        db_ok = False
    return {"status": "ok" if db_ok else "degraded", "database": db_ok}


@router.get("/recipes", response_model=list[RecipeOut], tags=["catalog"])
def list_recipes() -> list[RecipeOut]:
    """The recipe library families pick anchor meals from."""
    return [
        RecipeOut(
            id=r.id,
            name=r.name,
            cuisine=r.cuisine,
            diets=list(r.diets),
            core=r.id in CORE_IDS,
            ingredients=[
                IngredientOut(
                    name=i.name,
                    quantity=i.quantity,
                    unit=i.unit,
                    department=i.department,
                )
                for i in r.ingredients
            ],
        )
        for r in RECIPES
    ]


@router.get("/recipes/{rid}/steps", response_model=StepsOut, tags=["catalog"])
def recipe_steps(rid: str, db: Session = Depends(get_db)) -> StepsOut:
    """Cooking steps for a recipe, generated by Claude and cached.

    Returns source="unavailable" (not an error) when no API key is configured,
    so the UI can show a friendly message instead of failing.
    """
    recipe = RECIPES_BY_ID.get(rid)
    if not recipe:
        raise HTTPException(status_code=404, detail="Recipe not found")

    cached = db.get(RecipeSteps, rid)
    if cached:
        return StepsOut(steps=cached.steps, source="cached")

    if not llm.is_available():
        return StepsOut(steps=[], source="unavailable")

    try:
        steps = llm.generate_steps(
            recipe.name,
            [
                {"name": i.name, "quantity": i.quantity, "unit": i.unit}
                for i in recipe.ingredients
            ],
        )
    except Exception as e:  # never fail the request over an LLM hiccup
        return StepsOut(steps=[], source="error", detail=str(e))

    db.add(RecipeSteps(recipe_id=rid, steps=steps))
    db.commit()
    return StepsOut(steps=steps, source="claude")


@router.get("/coupons", response_model=list[Coupon], tags=["catalog"])
def list_coupons() -> list[Coupon]:
    """This week's H-E-B ad coupons (sample data in v1)."""
    return [Coupon(**c) for c in coupons.current()]


@router.post("/plans", response_model=PlanOut, tags=["plans"])
def create_plan(body: PlanRequestIn, db: Session = Depends(get_db)) -> PlanOut:
    """Generate a weekly plan + consolidated H-E-B shopping list, and store it."""
    plan = generate_plan(
        PlanRequest(
            household_size=body.household_size,
            meal_types=body.meal_types,
            cuisines=body.cuisines,
            diet=body.diet,
            anchor_meal_ids=body.anchor_meal_ids,
            pantry_exclude=body.pantry_exclude,
            budget=body.budget,
        )
    )
    if not plan["meals"]:
        raise HTTPException(
            status_code=422,
            detail="No meals matched the requested cuisines/diet. Widen the filters.",
        )

    row = Plan(household_id=body.household_id, week=plan["week"], payload=plan)
    db.add(row)
    db.commit()
    db.refresh(row)

    return PlanOut(id=row.id, **plan)


@router.get("/plans/{plan_id}", response_model=PlanOut, tags=["plans"])
def get_plan(plan_id: int, db: Session = Depends(get_db)) -> PlanOut:
    row = db.get(Plan, plan_id)
    if not row:
        raise HTTPException(status_code=404, detail="Plan not found")
    return PlanOut(id=row.id, **row.payload)
